global using AutoFixture;
global using AutoFixture.AutoMoq;
global using AutoMapper;
global using FluentAssertions;
global using Profit.Domain.Entities;
global using Profit.Domain.Profiles;
global using Profit.Domain.ValueObjects;
global using Profit.UnitTests.Fixtures;
global using Xunit;
