global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Profit.API.Endpoints;
global using Profit.DependencyInjection.Injectors;
global using Profit.Domain.Commands.Ingredient.Create;
global using Profit.Domain.Commands.Ingredient.CreateMany;
global using Profit.Domain.Commands.Ingredient.Delete;
global using Profit.Domain.Commands.Ingredient.Patch;
global using Profit.Domain.Commands.Ingredient.Put;
global using Profit.Domain.Exceptions;
global using Profit.Domain.Queries.Ingredient.GetMany;
global using Profit.Domain.Queries.Ingredient.GetUnique;
global using Profit.Infrastructure.Repository.DataContext;
global using Serilog;
global using System.Net;
global using System.Text.Json;
global using static Profit.Core.Constants;
global using ExceptionHandlerMiddleware = Profit.API.Middlewares.ExceptionHandlerMiddleware;
